# model params
model_name : arc_tf
backbone: ResNet50
headtype: NormHead
loss    : arcloss

#-------------------
##input config
image_size: 112
embd_size: 128
class_num: 5000
sample_num: 100000
#
##-------------------
## hyper params
weight_decay: !!float 5e-4
logits_scale: 64
logits_margin: 0.5

##-------------------
#optimizer
optimizer: SGD
momentum: 0.9
base_lr : 0.1
decay   : True
lr_steps: [20000,28000]
lr_values: [0,01, 0.001]
step_size: 50

##--------------------
## run params
batch_size: 64
init_epoch: 0
epoch_num: 20
step_per_epoch: 2000
# paths <SHOULD JUST CHANGE TRAIN DATA!>

train_data: "C:/Users/84982/Documents/GitHub/arcface_experiment/data/trainDS.tfrecord"
valid_data: "C:/Users/84982/Documents/GitHub/arcface_experiment/data/validDS.tfrecord"
test_data: "C:/Users/84982/Documents/GitHub/arcface_experiment/data/lfwdata.tfrecord"
save_dir : 'C:/Users/84982/Documents/GitHub/arcface_experiment/save'