# model params
model_name : softmax
backbone: resnet50
loss    : softmax
criterion: crossentropy
#-------------------
##input config
image_size: 112
embd_size: 512
class_num: 500
sample_num: 25000
#
##-------------------
## hyper params
weight_decay: !!float 5e-4
logits_scale: 64
logits_margin: 0.5

##-------------------
#optimizer
optimizer: SGD
momentum: 0.9
base_lr : 0.01
lr_steps: [0.5, 1]

##--------------------
## run params
batch_size: 16
init_epoch: 0
epoch_num: 50
step_per_save: epoch
# paths <SHOULD JUST CHANGE TRAIN DATA!>

train_data: "C:/Users/84982/Documents/GitHub/arcface_experiment/data/trainDS.tfrecord"
valid_data: "C:/Users/84982/Documents/GitHub/arcface_experiment/data/validDS.tfrecord"
test_data: "C:/Users/84982/Documents/GitHub/arcface_experiment/data/lfwdata.tfrecord"
save_dir : 'C:/Users/84982/Documents/GitHub/arcface_experiment/save'